//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::stmt
{
class expression : public stmt::statement
{
public:
    expression(
    std::unique_ptr<repr::expression> expr0
    ) :
        expr0(std::move(expr0))
    {}

    ~expression() = default;

    const repr::expression& get_expr0() const { return *expr0; }

private:
    std::unique_ptr<repr::expression> expr0;

    std::any accept(const visitor& visitor) const
    {
        return visitor.visit_expression_statement(*this);
    }
};
}