//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::stmt
{
class print : public stmt::statement
{
public:
    print(
    std::unique_ptr<repr::expression> expr0
    ) :
        expr0(std::move(expr0))
    {}

    ~print() = default;

    const repr::expression& get_expr0() const { return *expr0; }

private:
    std::unique_ptr<repr::expression> expr0;

    std::any accept(const stmt_visitor& visitor) const
    {
        return visitor.visit_print_statement(this);
    }
};
}