//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	class binary : public repr::expression
	{
	public:
		binary(
		std::unique_ptr<repr::expression> expr0,
		std::unique_ptr<repr::opr> expr1,
		std::unique_ptr<repr::expression> expr2
		) : 
			expr0(std::move(expr0)),
			expr1(std::move(expr1)),
			expr2(std::move(expr2))
		{}

~binary() = default;

	private:
		std::unique_ptr<repr::expression> expr0;
		std::unique_ptr<repr::opr> expr1;
		std::unique_ptr<repr::expression> expr2;

		std::any accept(const visitor& visitor) const
		{
			return visitor.visit_binary_expr(*this);
		}
	};
}