//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	class grouping : public repr::expression
	{
	public:
		grouping(
		std::unique_ptr<repr::expression> expr0
		) : 
			expr0(std::move(expr0))
		{}

		~grouping() = default;

		const repr::expression& get_expr0() const { return *expr0; }

	private:
		std::unique_ptr<repr::expression> expr0;

		std::any accept(const visitor& visitor) const
		{
			return visitor.visit_grouping_expr(this);
		}
	};
}