//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	template <class T>
	class grouping : public repr::expression<T>
	{
	public:
		grouping(
		std::unique_ptr<repr::expression<T>> expr0
		) : 
			expr0(std::move(expr0))
		{}

~grouping() = default;

	private:
		std::unique_ptr<repr::expression<T>> expr0;

		T accept(const visitor<T>& visitor) const
		{
			return visitor.visit_grouping_expr(*this);
		}
	};
}