//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
    template <class T>
    class opr : glox::repr::expression<T>
    {
    public:
        opr(
                glox::scanner::token expr0
        ) :
                expr0(std::move(expr0))
        {}
    private:
        glox::scanner::token expr0;

        T accept(visitor<T> visitor)
        {
            return visitor.visit_opr_expr();
        }
    };
}
