//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	class opr : public repr::expression
	{
	public:
		opr(
		std::unique_ptr<scanner::token> expr0
		) : 
			expr0(std::move(expr0))
		{}

~opr() = default;

	private:
		std::unique_ptr<scanner::token> expr0;

		std::any accept(const visitor& visitor) const
		{
			return visitor.visit_opr_expr(*this);
		}
	};
}