//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	template <class T>
	class string_literal : public repr::expression<T>
	{
	public:
		string_literal(
		std::unique_ptr<std::string<T>> expr0
		) : 
			expr0(std::move(expr0))
		{}

~string_literal() = default;

	private:
		std::unique_ptr<std::string<T>> expr0;

		T accept(const visitor<T>& visitor) const
		{
			return visitor.visit_string_literal_expr(*this);
		}
	};
}