//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	class string_literal : public repr::expression
	{
	public:
		string_literal(
		std::unique_ptr<std::string> expr0
		) : 
			expr0(std::move(expr0))
		{}

~string_literal() = default;

	private:
		std::unique_ptr<std::string> expr0;

		std::any accept(const visitor& visitor) const
		{
			return visitor.visit_string_literal_expr(*this);
		}
	};
}