//
// Auto-generated by Goksu Guvendiren Bakir. 
//

#pragma once

#include <utility>
#include "../token.hpp"
#include "expression.hpp"

namespace glox::repr
{
	class variable : public repr::expression
	{
	public:
		variable(
		std::unique_ptr<scanner::token> expr0
		) : 
			expr0(std::move(expr0))
		{}

		~variable() = default;

		const scanner::token& get_expr0() const { return *expr0; }

	private:
		std::unique_ptr<scanner::token> expr0;

		std::any accept(const visitor& visitor) const
		{
			return visitor.visit_variable_expr(this);
		}
	};
}